### ISSUE TITLE
only allow app to start once user has allow camera access and cursor disabling

### ISSUE THREAD

**Issue by roryc89** [realTalkTeam/realTalk#126]

**Comment by davemun** [comment]
"P" event listener doesn't work on Chrome?

**Comment by davemun** [comment]
Update: its not that the event listener doesn't work in Chrome, its that the webrtc method startLocalVideo() doesn't work in Chrome.

**Comment by davemun** [comment]
Implemented in 945f9a0c15d15a30319bea6eacd7b9e698fa6969, just going to have decreased Chrome support.
